name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Qowface
main: ${project.mainClass}
commands:
  swagadmin:
    description: Toggle admin tools.
    usage: "Usage: /<command>"
    permission: swagchest.admin
permissions:
  swagchest.admin:
    description: Allows SwagChest administration.
    default: op
